### ISSUE TITLE
Special Judge 壞掉了

### ISSUE THREAD

**Issue by rurutoria7** [TFcis/NTOJ#10]
<img width="1053" alt="image" src="https://github.com/TFcis/NTOJ/assets/91071151/0953fd68-88de-4328-a995-ca825f4e8f77">

該題是因為 special judge 不能使用所以卡 challenge 嗎

**Comment by tobiichi3227** [comment]
對，目前看下來基於ioredir的special judge都爛掉了
~~(問一下，我可以把judge換成TIOJ的嗎？~~

**Comment by tobiichi3227** [comment]
似乎是因為Judge是跑在Docker上的關係
