### ISSUE TITLE
Challist與Proset的分頁標籤在手機上的顯示異常

### ISSUE THREAD

**Issue by tobiichi3227** [TFcis/NTOJ#32]
如圖
![image](https://github.com/TFcis/NTOJ/assets/86729076/514c0861-58c5-499a-8064-b49fef8ce700)

**Comment by tobiichi3227** [comment]
@LifeAdventurer 這個問題給你處理
https://github.com/TFcis/NTOJ/blob/v2.0/src/static/templ/challist.html#L225

**Comment by lifeadventurer** [comment]
I'll deal with it when I have time.

**Comment by tobiichi3227** [comment]
Thanks.
