### ISSUE TITLE
遺忘帳號密碼無法登入

### ISSUE THREAD

**Issue by FRCnelson** [TFcis/NTOJ#58]
![image](https://github.com/TFcis/NTOJ/assets/125979974/5d8f715f-9dc4-4cf3-8626-28e92e009776)

這是我其中一隻帳號,但因為遺忘密碼而無法登入,想請管理員協助

mail: rudynelson70220@gmail.com

**Comment by tobiichi3227** [comment]
已經將新密碼傳到您的mail了
請確認是否可以登入

**Comment by FRCnelson** [comment]
還是無法登入成功........

**Comment by tobiichi3227** [comment]
請給正確的帳號啊......
你要改密碼的帳號跟你圖片提供的不相同
密碼已經改了，跟mail給的一樣
